/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebank_client;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.lang.Exception;
import java.util.List;

/**
 *
 * @author USER
 */
public class EmployeesListUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginUI
     */
    public EmployeesListUI() throws Exception {

        initComponents();

        // read the header image as a BufferedImage
        BufferedImage img1 = null;
        try {
            img1 = ImageIO.read(new File("images/LongHeader.jpg"));
        } catch (IOException e) {
            // error message
            JOptionPane.showMessageDialog(new JFrame(), "Loading image for Reel 1 failed", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        // resize the BufferedImage
        //Image dimg1 = img1.getScaledInstance(510, 90, BufferedImage.SCALE_SMOOTH);
        Image dimg1 = img1.getScaledInstance(lblHeader.getWidth(), lblHeader.getHeight() + 10, BufferedImage.SCALE_SMOOTH);

        // assign to reel label
        ImageIcon imageIcon1 = new ImageIcon(dimg1);
        lblHeader.setIcon(imageIcon1);

        // stored employee records as elements of arraylist
        List<String> arrL = displayEmployees();

        // create a new array to store details
        String[] arr = new String[arrL.size()];

        // convert arraylist to array
        int ind = 0;
        for (String s : arrL) {
            arr[ind++] = s;
        }

        lstEmployees.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item X", "Item 2", "Item 3", "Item 4", "Item 5" };

            String[] strings = arr;

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        jScrollPane1.setViewportView(lstEmployees);

    }

    // set & get from text fields
    public void setUsername(String username) {
        this.txtUsername.setText(username);
    }

    public String getUsername() {
        return this.txtUsername.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnSelect = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEmployees = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();

        setLocation(new java.awt.Point(500, 200));
        setResizable(false);

        jLabel1.setText("Username");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        btnSelect.setText("Select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(185, 6, 65));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Available Employees");

        lstEmployees.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lstEmployees.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstEmployees.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstEmployees.setFixedCellHeight(30);
        lstEmployees.setOpaque(false);
        lstEmployees.setSelectionBackground(new java.awt.Color(51, 51, 51));
        lstEmployees.setSelectionForeground(new java.awt.Color(204, 204, 204));
        lstEmployees.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lstEmployeesPropertyChange(evt);
            }
        });
        lstEmployees.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEmployeesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstEmployees);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Name           |           Position           |           Username");

        lblHeader.setBackground(new java.awt.Color(0, 102, 102));
        lblHeader.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCreate)
                        .addGap(289, 289, 289))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnSelect))
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        try {
            // get details from GUI
            String username = getUsername();

            // check whether account number is specified
            if (!username.isEmpty()) {

                // account number is given
                // redirect to view specific customer details
                // data, that should be loaded on text fields of customer account UI, when creating
                ArrayList<String> cDetails = null;
                cDetails = selectEmployee(username);

                String[] createDetails = new String[cDetails.size()];

                // convert to array
                int i = 0;
                for (String cD : cDetails) {
                    createDetails[i] = cD;
                    i++;
                }

                if (cDetails.size() == 0) {
                    // no relevant data loaded
                    throw new Exception("No matching record found for selection");
                } else {
                    // go to customer account page
                    EmployeePageUI employeePageUI = new EmployeePageUI(createDetails[0], createDetails[1], createDetails[2], createDetails[3]);
                    employeePageUI.setVisible(true);

                    this.setVisible(false);
                }

            } else {

                // account number not specified
                throw new Exception("Please specify the username to select");

            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(new JFrame(), ex.getLocalizedMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_btnSelectActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        try {
            // get username from GUI
            String username = getUsername();

            if (!username.isEmpty()) {
                // username specified

                // redirect to view specific employee details
                // data, that should be loaded on text fields of employee UI, when creating
                ArrayList<String> cDetails = null;
                cDetails = selectEmployee(username);

                String[] createDetails = new String[cDetails.size()];

                // convert to array
                int i = 0;
                for (String cD : cDetails) {
                    createDetails[i++] = cD;
                }

                // check for existing record in the given username
                if (cDetails.size() == 0) {
                    // no record available
                    // can create an employee with that username
                    EmployeePageUI employeePageUI = new EmployeePageUI("", "", username, "");
                    employeePageUI.setVisible(true);

                    this.setVisible(false);

                } else {

                    // record available
                    throw new Exception("There is already a record available with this Username");

                }

            } else {
                // username not specified
                throw new Exception("Please specify the username to create");
            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(new JFrame(), ex.getLocalizedMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void lstEmployeesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lstEmployeesPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lstEmployeesPropertyChange

    private void lstEmployeesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEmployeesValueChanged

        // get the selected string
        String selection = lstEmployees.getSelectedValue();

        // split the string to get username
        String[] selectionSplit = selection.split("           ");

        // assign username GUI
        txtUsername.setText(selectionSplit[2]);


    }//GEN-LAST:event_lstEmployeesValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JList<String> lstEmployees;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private static java.util.ArrayList<java.lang.String> displayEmployees() throws Exception {
        EBank_Client_Employee.EBankEmployeeWS_Service service = new EBank_Client_Employee.EBankEmployeeWS_Service();
        EBank_Client_Employee.EBankEmployeeWS port = service.getEBankEmployeeWSPort();
        return port.displayEmployees();
    }

    private static java.util.ArrayList<java.lang.String> selectEmployee(java.lang.String username) throws Exception {
        EBank_Client_Employee.EBankEmployeeWS_Service service = new EBank_Client_Employee.EBankEmployeeWS_Service();
        EBank_Client_Employee.EBankEmployeeWS port = service.getEBankEmployeeWSPort();
        return port.selectEmployee(username);
    }
}
