/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebank_client;

import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.lang.Exception;

/**
 *
 * @author USER
 */
public class EmployeePageUI extends javax.swing.JFrame {

    /**
     * Creates new form CustomerAccountPageUI
     *
     * @param controller
     * @param name
     * @param position
     * @param username
     * @param password
     */
    public EmployeePageUI(String name, String position, String username, String password) {

        initComponents();

        // read the header image as a BufferedImage
        BufferedImage img1 = null;
        try {
            img1 = ImageIO.read(new File("images/ShortHeader.jpg"));
        } catch (IOException e) {
            // error message
            JOptionPane.showMessageDialog(new JFrame(), "Loading image for Reel 1 failed", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        // resize the BufferedImage
        //Image dimg1 = img1.getScaledInstance(510, 90, BufferedImage.SCALE_SMOOTH);
        Image dimg1 = img1.getScaledInstance(lblHeader.getWidth(), lblHeader.getHeight() + 10, BufferedImage.SCALE_SMOOTH);

        // assign to reel label
        ImageIcon imageIcon1 = new ImageIcon(dimg1);
        lblHeader.setIcon(imageIcon1);

        // initialize fields with constructed data
        txtName.setText(name);
        txtPosition.setText(position);
        txtUsername.setText(username);
        txtPassword.setText(password);

        // disable username field and buttons
        // if all the fields are filled, then only edit / delete is possible
        if (!name.isEmpty() && !position.isEmpty() && !username.isEmpty() && !password.isEmpty()) {
            btnCreate.setEnabled(false);
            btnDelete.setEnabled(true);
            btnEdit.setEnabled(true);
            txtUsername.setEnabled(false);
        } else {
            // username only available (no other situation is possible)
            // only create is possible
            btnCreate.setEnabled(true);

            btnDelete.setEnabled(false);
            btnEdit.setEnabled(false);
            txtUsername.setEnabled(true);
        }

    }

    // set & get from text fields
    public void setName(String name) {
        this.txtName.setText(name);
    }

    public void setPosition(String position) {
        this.txtPosition.setText(position);
    }

    public void setUsername(String username) {
        this.txtUsername.setText(username);
    }

    public void setPassword(String password) {
        this.txtPassword.setText(password);
    }

    public String getName() {
        return this.txtName.getText();
    }

    public String getPosition() {
        return this.txtPosition.getText();
    }

    public String getUsername() {
        return this.txtUsername.getText();
    }

    public String getPassword() {
        return this.txtPassword.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();

        setLocation(new java.awt.Point(500, 200));
        setResizable(false);

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        jLabel1.setText("Name :");

        jLabel2.setText("Position :");

        jLabel3.setText("Username :");

        jLabel4.setText("Password :");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(185, 6, 65));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Employee Details");

        lblHeader.setBackground(new java.awt.Color(0, 102, 102));
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addGap(18, 18, 18)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(jLabel15)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {

            // user logged in
            // get details entered from GUI
            String name = getName();
            String position = getPosition();
            String username = getUsername();
            String password = getPassword();

            // validations
            if (name.isEmpty() || position.isEmpty() || username.isEmpty() || password.isEmpty()) {

                throw new Exception("Please fill out all the fields");

            } else {

                // update table record, username unchanged
                editEmployee(name, position, username, password);
                JOptionPane.showMessageDialog(new JFrame(), "Successfully Updated!", "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                EmployeesListUI employeesListUI = new EmployeesListUI();
                employeesListUI.setVisible(true);

                this.setVisible(false);
            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(new JFrame(), ex.getLocalizedMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        try {

            // user logged in
            // get details entered from GUI
            String name = getName();
            String position = getPosition();
            String username = getUsername();
            String password = getPassword();

            // validations
            if (name.isEmpty() || position.isEmpty() || username.isEmpty() || password.isEmpty()) {

                throw new Exception("Please fill out all the fields");

            } else {

                // create a record in table with entered details
                createEmployee(name, position, username, password);
                JOptionPane.showMessageDialog(new JFrame(), "Successfully Created!", "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                EmployeesListUI employeesListUI = new EmployeesListUI();
                employeesListUI.setVisible(true);

                this.setVisible(false);

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getLocalizedMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        try {

            // user logged in
            // get details entered from GUI
            String username = getUsername();

            if (username.isEmpty()) {
                // no username specified
                throw new Exception("Please specify the username to delete");

            } else {

                // delete record from table, that has the given username
                deleteEmployee(username);

                JOptionPane.showMessageDialog(new JFrame(), "Successfully Deleted!", "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                EmployeesListUI employeesListUI = new EmployeesListUI();
                employeesListUI.setVisible(true);

                this.setVisible(false);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getLocalizedMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private static int createEmployee(java.lang.String name, java.lang.String position, java.lang.String username, java.lang.String password) throws Exception {
        EBank_Client_Employee.EBankEmployeeWS_Service service = new EBank_Client_Employee.EBankEmployeeWS_Service();
        EBank_Client_Employee.EBankEmployeeWS port = service.getEBankEmployeeWSPort();
        return port.createEmployee(name, position, username, password);
    }

    private static int editEmployee(java.lang.String name, java.lang.String position, java.lang.String username, java.lang.String password) throws Exception {
        EBank_Client_Employee.EBankEmployeeWS_Service service = new EBank_Client_Employee.EBankEmployeeWS_Service();
        EBank_Client_Employee.EBankEmployeeWS port = service.getEBankEmployeeWSPort();
        return port.editEmployee(name, position, username, password);
    }

    private static int deleteEmployee(java.lang.String username) throws Exception {
        EBank_Client_Employee.EBankEmployeeWS_Service service = new EBank_Client_Employee.EBankEmployeeWS_Service();
        EBank_Client_Employee.EBankEmployeeWS port = service.getEBankEmployeeWSPort();
        return port.deleteEmployee(username);
    }
}
