/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebank_client;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.lang.Exception;
import java.util.ArrayList;

/**
 *
 * @author USER
 */
public class LoginUI extends javax.swing.JFrame {

    //Controller control;
    /**
     * Creates new form LoginUI
     */
    public LoginUI() {

        // logged out at beginning
        Session.isLoggedIn = false;
        initComponents();

        // username label
        if (Session.username == null) {

            // username label
            statusLabel.setText("Register");

        } else {

            // username label
            statusLabel.setText(Session.username);

        }

        // check for login status
        if (!Session.isLoggedIn) {

            // not logged in
            // disable logout button
            btnLogout.setEnabled(false);

        }

        // read the header image as a BufferedImage
        BufferedImage img1 = null;
        try {
            img1 = ImageIO.read(new File("images/ShortHeader.jpg"));
        } catch (IOException e) {
            // error message
            JOptionPane.showMessageDialog(new JFrame(), "Loading image for Reel 1 failed", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        // resize the BufferedImage
        //Image dimg1 = img1.getScaledInstance(510, 90, BufferedImage.SCALE_SMOOTH);
        Image dimg1 = img1.getScaledInstance(lblHeader.getWidth(), lblHeader.getHeight() + 10, BufferedImage.SCALE_SMOOTH);

        // assign to reel label
        ImageIcon imageIcon1 = new ImageIcon(dimg1);
        lblHeader.setIcon(imageIcon1);
    }

    // set & get from text fields
    public void setUsername(String username) {
        this.txtUsername.setText(username);
    }

    public String getUsername() {
        return this.txtUsername.getText();
    }

    public void setPassword(String password) {
        this.txtPassword.setText(password);
    }

    public String getPassword() {
        return this.txtPassword.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnEmployees = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();

        setLocation(new java.awt.Point(500, 200));
        setResizable(false);

        jLabel1.setText("Username :");

        jLabel2.setText("Password :");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(185, 6, 65));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Employee Login");

        btnEmployees.setText("Employees");
        btnEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeesActionPerformed(evt);
            }
        });

        lblHeader.setBackground(new java.awt.Color(0, 102, 102));
        lblHeader.setOpaque(true);

        statusLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(185, 6, 65));
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        statusLabel.setText(" ");
        statusLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statusLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPassword)
                    .addComponent(txtUsername)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEmployees)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnLogout)
                    .addComponent(btnEmployees))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(statusLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        // logging in again is logging out the previous user
        Session.isLoggedIn = false;

        try {
            // get username & password from GUI
            String username = getUsername();
            String password = getPassword();

            if (username.isEmpty()) {
                // no username entered
                throw new Exception("Please provide the username");
            } else {
                // username entered
                String loginStatus = login(username, password);

                if (loginStatus.equals("success")) {

                    // correct username & password
                    Session.isLoggedIn = true;
                    Session.username = username;

                    // username label
                    statusLabel.setText(Session.username);

                    // get name for the specified username for welcome prompt
                    ArrayList<String> uDetails = null;
                    uDetails = selectEmployee(username);

                    String[] userDetails = new String[uDetails.size()];

                    // convert to array
                    int i = 0;
                    for (String uD : uDetails) {
                        userDetails[i++] = uD;
                    }

                    // welcome message
                    JOptionPane.showMessageDialog(new JFrame(), "Welcome " + userDetails[0] + " !", "Welcome",
                            JOptionPane.INFORMATION_MESSAGE);

                    // load customer list UI
                    CustomersListUI customersListUI = new CustomersListUI();
                    customersListUI.setVisible(true);

                    // enable logout button
                    btnLogout.setEnabled(true);

                } else if (loginStatus.equals("invalid")) {

                    // invalid combination of username & password
                    throw new Exception("Invalid Password");

                } else if (loginStatus.equals("noUser")) {

                    // no user found in the name
                    throw new Exception("No user found with the given username");

                }
            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(new JFrame(), ex.getLocalizedMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try {
            Session.isLoggedIn = false;
            Session.username = null;
            // username label
            statusLabel.setText("Register");

            // enable Register button
            btnEmployees.setEnabled(true);

            // disable Logout button
            btnLogout.setEnabled(false);

            JOptionPane.showMessageDialog(new JFrame(), "Logged Out successfully!", "Success",
                    JOptionPane.INFORMATION_MESSAGE);
//            System.exit(0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getLocalizedMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeesActionPerformed
        try {
            EmployeesListUI employeesListUI = new EmployeesListUI();
            employeesListUI.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getLocalizedMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEmployeesActionPerformed

    private void statusLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusLabelMouseClicked

        if (!Session.isLoggedIn) {
            try {

                EmployeePageUI employeePageUI = new EmployeePageUI("", "", "", "");
                employeePageUI.setVisible(true);

            } catch (Exception ex) {

                JOptionPane.showMessageDialog(new JFrame(), ex.getLocalizedMessage(), "Error",
                        JOptionPane.ERROR_MESSAGE);

            }
        }


    }//GEN-LAST:event_statusLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmployees;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private static String login(java.lang.String username, java.lang.String password) throws Exception {
        EBank_Client_Employee.EBankEmployeeWS_Service service = new EBank_Client_Employee.EBankEmployeeWS_Service();
        EBank_Client_Employee.EBankEmployeeWS port = service.getEBankEmployeeWSPort();
        return port.login(username, password);
    }

    private static java.util.ArrayList<java.lang.String> selectEmployee(java.lang.String username) throws Exception {
        EBank_Client_Employee.EBankEmployeeWS_Service service = new EBank_Client_Employee.EBankEmployeeWS_Service();
        EBank_Client_Employee.EBankEmployeeWS port = service.getEBankEmployeeWSPort();
        return port.selectEmployee(username);
    }

}
