
package EBank_Client_Customer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EBankCustomer_WS", targetNamespace = "http://ebankCustomer_ws/", wsdlLocation = "http://localhost:29070/EBankCustomer_WS/EBankCustomer_WS?wsdl")
public class EBankCustomerWS_Service
    extends Service
{

    private final static URL EBANKCUSTOMERWS_WSDL_LOCATION;
    private final static WebServiceException EBANKCUSTOMERWS_EXCEPTION;
    private final static QName EBANKCUSTOMERWS_QNAME = new QName("http://ebankCustomer_ws/", "EBankCustomer_WS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:29070/EBankCustomer_WS/EBankCustomer_WS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EBANKCUSTOMERWS_WSDL_LOCATION = url;
        EBANKCUSTOMERWS_EXCEPTION = e;
    }

    public EBankCustomerWS_Service() {
        super(__getWsdlLocation(), EBANKCUSTOMERWS_QNAME);
    }

    public EBankCustomerWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EBANKCUSTOMERWS_QNAME, features);
    }

    public EBankCustomerWS_Service(URL wsdlLocation) {
        super(wsdlLocation, EBANKCUSTOMERWS_QNAME);
    }

    public EBankCustomerWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EBANKCUSTOMERWS_QNAME, features);
    }

    public EBankCustomerWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EBankCustomerWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EBankCustomerWS
     */
    @WebEndpoint(name = "EBankCustomer_WSPort")
    public EBankCustomerWS getEBankCustomerWSPort() {
        return super.getPort(new QName("http://ebankCustomer_ws/", "EBankCustomer_WSPort"), EBankCustomerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EBankCustomerWS
     */
    @WebEndpoint(name = "EBankCustomer_WSPort")
    public EBankCustomerWS getEBankCustomerWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ebankCustomer_ws/", "EBankCustomer_WSPort"), EBankCustomerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EBANKCUSTOMERWS_EXCEPTION!= null) {
            throw EBANKCUSTOMERWS_EXCEPTION;
        }
        return EBANKCUSTOMERWS_WSDL_LOCATION;
    }

}
