
package EBank_Client_Customer;

import java.util.ArrayList;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EBankCustomer_WS", targetNamespace = "http://ebankCustomer_ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EBankCustomerWS {


    /**
     * 
     * @param field
     * @param value
     * @param table
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkAvailability", targetNamespace = "http://ebankCustomer_ws/", className = "EBank_Client_Customer.CheckAvailability")
    @ResponseWrapper(localName = "checkAvailabilityResponse", targetNamespace = "http://ebankCustomer_ws/", className = "EBank_Client_Customer.CheckAvailabilityResponse")
    @Action(input = "http://ebankCustomer_ws/EBankCustomer_WS/checkAvailabilityRequest", output = "http://ebankCustomer_ws/EBankCustomer_WS/checkAvailabilityResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ebankCustomer_ws/EBankCustomer_WS/checkAvailability/Fault/Exception")
    })
    public boolean checkAvailability(
        @WebParam(name = "field", targetNamespace = "")
        String field,
        @WebParam(name = "value", targetNamespace = "")
        String value,
        @WebParam(name = "table", targetNamespace = "")
        String table)
        throws Exception_Exception
    ;

    /**
     * 
     * @param accountNumber
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectCustomer", targetNamespace = "http://ebankCustomer_ws/", className = "EBank_Client_Customer.SelectCustomer")
    @ResponseWrapper(localName = "selectCustomerResponse", targetNamespace = "http://ebankCustomer_ws/", className = "EBank_Client_Customer.SelectCustomerResponse")
    @Action(input = "http://ebankCustomer_ws/EBankCustomer_WS/selectCustomerRequest", output = "http://ebankCustomer_ws/EBankCustomer_WS/selectCustomerResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ebankCustomer_ws/EBankCustomer_WS/selectCustomer/Fault/Exception")
    })
    public ArrayList<String> selectCustomer(
        @WebParam(name = "accountNumber", targetNamespace = "")
        String accountNumber)
        throws Exception_Exception
    ;

    /**
     * 
     * @param address
     * @param balance
     * @param accountType
     * @param name
     * @param mobile
     * @param accountNumber
     * @param birthDate
     * @param sortCode
     * @param email
     * @param card
     * @return
     *     returns int
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createCustomer", targetNamespace = "http://ebankCustomer_ws/", className = "EBank_Client_Customer.CreateCustomer")
    @ResponseWrapper(localName = "createCustomerResponse", targetNamespace = "http://ebankCustomer_ws/", className = "EBank_Client_Customer.CreateCustomerResponse")
    @Action(input = "http://ebankCustomer_ws/EBankCustomer_WS/createCustomerRequest", output = "http://ebankCustomer_ws/EBankCustomer_WS/createCustomerResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ebankCustomer_ws/EBankCustomer_WS/createCustomer/Fault/Exception")
    })
    public int createCustomer(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "birthDate", targetNamespace = "")
        String birthDate,
        @WebParam(name = "address", targetNamespace = "")
        String address,
        @WebParam(name = "mobile", targetNamespace = "")
        String mobile,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "accountType", targetNamespace = "")
        String accountType,
        @WebParam(name = "accountNumber", targetNamespace = "")
        String accountNumber,
        @WebParam(name = "sortCode", targetNamespace = "")
        String sortCode,
        @WebParam(name = "balance", targetNamespace = "")
        double balance,
        @WebParam(name = "card", targetNamespace = "")
        String card)
        throws Exception_Exception
    ;

    /**
     * 
     * @param address
     * @param balance
     * @param accountType
     * @param name
     * @param mobile
     * @param accountNumber
     * @param birthDate
     * @param sortCode
     * @param email
     * @param card
     * @return
     *     returns int
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editCustomer", targetNamespace = "http://ebankCustomer_ws/", className = "EBank_Client_Customer.EditCustomer")
    @ResponseWrapper(localName = "editCustomerResponse", targetNamespace = "http://ebankCustomer_ws/", className = "EBank_Client_Customer.EditCustomerResponse")
    @Action(input = "http://ebankCustomer_ws/EBankCustomer_WS/editCustomerRequest", output = "http://ebankCustomer_ws/EBankCustomer_WS/editCustomerResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ebankCustomer_ws/EBankCustomer_WS/editCustomer/Fault/Exception")
    })
    public int editCustomer(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "birthDate", targetNamespace = "")
        String birthDate,
        @WebParam(name = "address", targetNamespace = "")
        String address,
        @WebParam(name = "mobile", targetNamespace = "")
        String mobile,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "accountType", targetNamespace = "")
        String accountType,
        @WebParam(name = "accountNumber", targetNamespace = "")
        String accountNumber,
        @WebParam(name = "sortCode", targetNamespace = "")
        String sortCode,
        @WebParam(name = "balance", targetNamespace = "")
        double balance,
        @WebParam(name = "card", targetNamespace = "")
        String card)
        throws Exception_Exception
    ;

    /**
     * 
     * @param accountNumber
     * @return
     *     returns int
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCustomer", targetNamespace = "http://ebankCustomer_ws/", className = "EBank_Client_Customer.DeleteCustomer")
    @ResponseWrapper(localName = "deleteCustomerResponse", targetNamespace = "http://ebankCustomer_ws/", className = "EBank_Client_Customer.DeleteCustomerResponse")
    @Action(input = "http://ebankCustomer_ws/EBankCustomer_WS/deleteCustomerRequest", output = "http://ebankCustomer_ws/EBankCustomer_WS/deleteCustomerResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ebankCustomer_ws/EBankCustomer_WS/deleteCustomer/Fault/Exception")
    })
    public int deleteCustomer(
        @WebParam(name = "accountNumber", targetNamespace = "")
        String accountNumber)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "displayCustomer", targetNamespace = "http://ebankCustomer_ws/", className = "EBank_Client_Customer.DisplayCustomer")
    @ResponseWrapper(localName = "displayCustomerResponse", targetNamespace = "http://ebankCustomer_ws/", className = "EBank_Client_Customer.DisplayCustomerResponse")
    @Action(input = "http://ebankCustomer_ws/EBankCustomer_WS/displayCustomerRequest", output = "http://ebankCustomer_ws/EBankCustomer_WS/displayCustomerResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ebankCustomer_ws/EBankCustomer_WS/displayCustomer/Fault/Exception")
    })
    public ArrayList<String> displayCustomer()
        throws Exception_Exception
    ;

}
